name: Submodule Update

on:
  schedule:
    - cron: '0 3 * * *'  # 每日凌晨3点执行
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          
      - name: Update submodules
        run: |
          git submodule update --recursive --remote
          
      - name: Commit changes
        run: |
          git config --global user.name "Automated Bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "Auto-update submodules" || echo "No changes to commit"
          git push
